data:
    data_dir:         data/REMIaligned_events
    train_split:      data/train.pkl
    val_split:        data/val.pkl
    test_split:       data/test.pkl
    vocab_path_melody:       data/dictionary_melody.pkl
    max_seqs:         64                 
    enc_seqlen:       128
    dec_seqlen:       2048               
    batch_size:       4

model:
    enc_n_layer:      12
    enc_n_head:       8
    enc_d_model:      512
    enc_d_ff:         2048
    dec_n_layer:      12
    dec_n_head:       8
    dec_d_model:      512
    dec_d_ff:         2048
    d_embed:          512
    d_latent:         128
    n_codes:          2048
    n_groups:         64
    pretrained_params_path:      null
    pretrained_optim_path:       null

training:
    device:           cuda:0
    ckpt_dir:         ./config/model_VQVAE
    trained_steps:    0
    max_epochs:       12
    max_lr:           1.0e-4
    min_lr:           5.0e-6
    lr_warmup_steps:  200
    lr_decay_steps:   150000
    no_kl_steps:      10000
    kl_cycle_steps:   5000
    kl_max_beta:      1.0
    free_bit_lambda:  0.25
    constant_kl:      False
    ckpt_interval:    1000
    log_interval:     10
    val_interval:     50

generate:
    temperature:                1.2
    nucleus_p:                  0.9
    use_latent_sampling:        False
    latent_sampling_var:        0.0
    max_seqs:                   64       # could be set to match the longest input piece during generation (inference)
    dec_seqlen:                 2048     # could be set to match the longest input piece during generation (inference)
    max_input_dec_seqlen:       2048     # should be set to equal to or less than `dec_seqlen` used during training